site_name: Customer churn reference implementation solution
repo_url: https://github.com/ibm-cloud-architecture/refarch-ai-data-customer-churn.git
nav:
  - Business problem: businessproblem.md
  - Solution: solution.md
  - Labs: 
    - IBM Cloud: lab/readme.md
    - IBM Cloud Pak for Data: lab-IBMCloudPakForData/readme.md
theme: 
  name: material
  logo: images/cloud.png
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
